### ISSUE TITLE
Create a Custom action to provide the shell script to validate the PR titles

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder-release-tools#62]
**Context:**

Refer to this [PR](https://github.com/kubernetes-sigs/kubebuilder-release-tools/pull/61).
Discussion thread: [Slack thread](https://kubernetes.slack.com/archives/CAR30FCJZ/p1726412434458119).

**Description:** We need to create a custom GitHub action that provides a shell script to validate PR titles. This would ensure consistency in PR naming conventions and improve the overall workflow.

**Idea**

We might need add here:

```
name: "PR Title Validator"
description: "Validates PR titles based on predefined conventions."
inputs:
  github-token:
    description: "GitHub Token"
    required: true
runs:
  using: "bash"
  main: "entrypoint.sh" <-- And add the shell script


```

therefore, people could use it like

```yaml
jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PR Title Validator from kubebuilder-release-tools
        uses: kubernetes-sigs/kubebuilder-release-tools/.github/actions/pr-title-checker@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
``` 

**Then we need to**
- Do the changes to provide the action
- Update the docs here: https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#pr-verification-github-action-deprecated accordingly.
